from fpdf import FPDF
import os
from datetime import datetime

class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Clinical Chest X-Ray AI Analysis Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_pdf(patient_data, prediction, confidence, severity, recs, original_path, heatmap_path):
    pdf = PDFReport()
    pdf.add_page()
    
    pdf.set_font("Arial", size=12)
    
    # Date and Doctor
    pdf.cell(200, 10, txt=f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=1)
    pdf.cell(200, 10, txt=f"Attending Doctor: {patient_data['doctor']}", ln=1)
    pdf.ln(5)
    
    # Patient Info
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="Patient Information:", ln=1)
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Name: {patient_data['name']}", ln=1)
    pdf.cell(200, 10, txt=f"Age: {patient_data['age']} | Gender: {patient_data['gender']}", ln=1)
    pdf.cell(200, 10, txt=f"Reported Symptoms: {patient_data['symptoms']}", ln=1)
    pdf.ln(5)
    
    # AI Results
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="AI Analysis Results:", ln=1)
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Prediction: {prediction}", ln=1)
    pdf.cell(200, 10, txt=f"Ensemble Confidence: {confidence:.2%}", ln=1)
    if prediction == "PNEUMONIA":
        pdf.cell(200, 10, txt=f"Estimated Severity: {severity}", ln=1)
    pdf.ln(5)
    
    # Recommendations
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="Clinical Recommendations:", ln=1)
    pdf.set_font("Arial", size=12)
    for rec in recs:
        pdf.cell(200, 10, txt=f"- {rec}", ln=1)
    pdf.ln(10)
    
    # Images
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="Imaging:", ln=1)
    
    # Add images side by side if possible
    y_before_img = pdf.get_y()
    if os.path.exists(original_path):
        pdf.image(original_path, x=10, y=y_before_img, w=80)
        pdf.text(x=35, y=y_before_img - 2, txt="Original X-Ray")
    if os.path.exists(heatmap_path):
        pdf.image(heatmap_path, x=100, y=y_before_img, w=80)
        pdf.text(x=120, y=y_before_img - 2, txt="Grad-CAM Heatmap")
        
    pdf.ln(90)
    pdf.set_font("Arial", 'I', 10)
    pdf.multi_cell(0, 10, "DISCLAIMER: This report is generated by an AI model and is for informational/portfolio purposes only. It is not a clinical diagnosis. All findings must be verified by a licensed radiologist.")

    filename = f"reports/Report_{patient_data['name'].replace(' ', '_')}_{datetime.now().strftime('%Y%m%d')}.pdf"
    os.makedirs("reports", exist_ok=True)
    pdf.output(filename)
    return filename
